; generated by PrusaSlicer 3.0.0-alpha on 2026-09-21 at 00:00:00 UTC
;
; ^^ That line is load-bearing, not decoration. Happy Hare's Moonraker
; preprocessor only runs on files matching SLICER_REGEX with a name in
; AUTHORZIED_SLICERS (mmu_server.py:1876). Without it the bare T<n> lines
; below are never rewritten and the toolchanges do nothing. This file was
; hand-written; the header is a trigger, not a claim about its origin.
;
; blobifier-swap-test.gcode
;
; Validates two changes to the Blobifier toolchange path:
;   1. pressure_release_time restored 1500 -> 750 (lost in the v4 migration)
;   2. a 2mm final_retract on the last blob that is deliberately NOT restored
;
; Assumes the machine is ALREADY HOMED. No bed heat, no mesh, no adhesion.
; NOTHING HERE EXTRUDES -- any filament that appears is ooze.
;
; Gates 0 and 1 are Polymaker ABS (255C). Three squares, two swaps, both
; directions, so there are two blob sets to cut open.
;
; Uses bare T<n> so the upload exercises the preprocessor's rewrite into
; MMU_CHANGE_TOOL ... NEXT_POS="x,y" -- the same path real prints take.

G90                     ; absolute XYZ
M83                     ; relative E, as HH/Blobifier expect
G1 Z100 F3000           ; well clear of the bed
G1 X175 Y175 F9000      ; centre
M109 S255               ; ABS -- wait for temp

; Runtime only: reverts on the next restart so a test value cannot quietly
; become permanent. 160 > purge_length_maximum (150), so this splits into
; 2 blobs of 80 -- which exercises BOTH the between-blobs 6mm retract and
; the new 2mm final retract.
SET_GCODE_VARIABLE MACRO=_BLOBIFIER_VARS VARIABLE=purge_length VALUE=160

; Raise Klipper's status tick for the duration (klippy_extras/knomi_query_refresh.py).
; Moves BOTH webhooks.SUBSCRIPTION_REFRESH_TIME and motion_report.STATUS_REFRESH_TIME,
; which have to change together or live_position is just re-fetched stale. 0.02 is the
; module's min_period and gives ~46Hz sampling. RESET=1 at the end -- and the module
; also restores on shutdown/disconnect, so a crash cannot strand the machine at 50Hz.
SET_QUERY_REFRESH PERIOD=0.02

; ---------- square 1: reference, current tool ----------
M118 >>> square 1 (reference)
G1 X135 Y135 F9000
G1 X215 Y135 F9000
G1 X215 Y215 F9000
G1 X135 Y215 F9000
G1 X135 Y135 F9000
G1 X175 Y175 F9000

; ---------- swap 0 -> 1 ----------
M400
G4 P500                 ; known still period -- subtract from the trace gap
M118 >>> swap 0->1 begins
T1
M118 >>> swap 0->1 returned, square 2 starts now
G1 X135 Y135 F9000
G1 X215 Y135 F9000
G1 X215 Y215 F9000
G1 X135 Y215 F9000
G1 X135 Y135 F9000
G1 X175 Y175 F9000

; ---------- swap 1 -> 0 ----------
M400
G4 P500                 ; known still period -- subtract from the trace gap
M118 >>> swap 1->0 begins
T0
M118 >>> swap 1->0 returned, square 3 starts now
G1 X135 Y135 F9000
G1 X215 Y135 F9000
G1 X215 Y215 F9000
G1 X135 Y215 F9000
G1 X135 Y135 F9000
G1 X175 Y175 F9000

M118 >>> test complete
SET_QUERY_REFRESH RESET=1
M104 S0
